name: 'Hello World'
description: 'Greet someone'
inputs:
  image:
    description: "image:tag"
    required: true
  target:
    description: "target:tag"
    required: true
  context:
    description: "context"
    required: true
    default: "."
outputs: {}
runs:
  using: "composite"
  steps:
    - run: |
        docker build -t ${{ inputs.image }} --target ${{ inputs.target }} ${{ inputs.context }}
      shell: bash